/* The following code was generated by JFlex 1.6.1 */

package scannercompi;
import static scannercompi.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/orlandojose/NetBeansProjects/ScannerCompi/src/scannercompi/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\1\17\1\17\1\4\22\0\1\3\1\0\1\11"+
    "\1\23\3\0\1\10\1\20\1\22\1\21\1\6\1\71\1\24\1\7"+
    "\1\16\4\15\4\14\2\2\1\70\1\67\1\66\1\65\1\64\2\0"+
    "\1\41\1\61\1\52\1\53\1\5\1\57\1\51\1\36\1\33\1\1"+
    "\1\56\1\37\1\54\1\43\1\26\1\46\1\1\1\27\1\50\1\34"+
    "\1\42\1\40\1\31\1\25\1\45\1\1\1\63\1\12\1\62\1\0"+
    "\1\1\1\0\1\41\1\13\1\52\1\53\1\5\1\60\1\51\1\36"+
    "\1\33\1\1\1\56\1\37\1\54\1\44\1\26\1\46\1\1\1\30"+
    "\1\50\1\35\1\42\1\40\1\31\1\25\1\45\1\1\12\0\1\17"+
    "\252\0\2\32\115\0\1\47\u1ea8\0\1\17\1\17\u0100\0\1\55\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\2\1\5\1\6"+
    "\2\1\1\2\1\7\1\10\1\11\1\12\1\1\1\13"+
    "\4\2\1\1\10\2\1\1\6\2\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\2\1\2\2\1\3"+
    "\1\24\1\0\1\25\1\1\3\0\1\26\1\0\3\2"+
    "\1\4\1\27\2\0\1\30\1\31\1\32\1\33\1\2"+
    "\1\34\1\35\2\2\1\0\2\2\1\36\1\37\1\36"+
    "\1\37\1\40\12\2\1\0\3\2\3\0\7\2\1\41"+
    "\1\0\3\2\1\0\3\2\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\1\1\50\1\0\1\2\1\51\1\0"+
    "\1\31\2\0\3\2\3\0\1\52\3\2\1\0\1\2"+
    "\1\0\1\2\1\0\1\2\1\53\1\0\1\53\6\2"+
    "\1\54\1\2\1\55\1\2\1\56\2\57\2\2\1\60"+
    "\2\0\1\60\5\2\1\0\2\2\2\61\1\62\1\63"+
    "\1\0\3\2\1\64\1\65\1\1\2\66\1\50\1\0"+
    "\2\2\1\67\1\4\1\3\1\70\1\71\2\2\1\0"+
    "\1\2\2\72\1\0\1\2\1\0\1\2\1\73\1\74"+
    "\1\75\3\2\1\0\3\2\1\0\1\2\2\0\2\2"+
    "\1\76\1\0\1\2\1\77\2\100\2\2\2\101\1\0"+
    "\2\2\1\50\2\0\2\102\3\2\2\103\2\104\1\0"+
    "\1\2\1\0\1\2\1\105\1\106\2\107\2\2\1\0"+
    "\1\2\2\0\2\2\2\110\2\2\2\111\1\2\1\50"+
    "\1\2\1\112\1\113\2\114\1\0\3\2\2\115\1\116"+
    "\1\0\1\116\1\2\1\117\1\2\1\0\1\2\1\120"+
    "\2\121\1\122\1\2\1\0\1\2\1\123\1\0\2\2"+
    "\2\124\2\125\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[309];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\72\0\350\0\u0122\0\u015c"+
    "\0\u0196\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\72\0\u02f2"+
    "\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2"+
    "\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692"+
    "\0\u06cc\0\u0706\0\u0740\0\u077a\0\u07b4\0\72\0\72\0\u07ee"+
    "\0\72\0\u0828\0\72\0\u0862\0\72\0\u089c\0\u08d6\0\u0910"+
    "\0\u094a\0\u0984\0\72\0\u09be\0\72\0\u015c\0\u09f8\0\u0a32"+
    "\0\u01d0\0\72\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\72"+
    "\0\u0b8e\0\u0bc8\0\72\0\u02f2\0\72\0\72\0\u0c02\0\164"+
    "\0\164\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\72"+
    "\0\u0d98\0\164\0\164\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\u0eba"+
    "\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u0fdc\0\u1016\0\u1050\0\u108a"+
    "\0\u10c4\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u125a"+
    "\0\u1294\0\u12ce\0\u1308\0\u1342\0\u137c\0\u13b6\0\u13f0\0\u142a"+
    "\0\u1464\0\u149e\0\u14d8\0\u1512\0\u154c\0\72\0\72\0\72"+
    "\0\u1586\0\72\0\u15c0\0\u15fa\0\u1634\0\u166e\0\164\0\u16a8"+
    "\0\72\0\u16e2\0\u171c\0\u1756\0\u1790\0\u17ca\0\u1804\0\u183e"+
    "\0\u1878\0\164\0\u18b2\0\u18ec\0\u1926\0\u1960\0\u199a\0\u19d4"+
    "\0\u1a0e\0\u1a48\0\u1a82\0\72\0\u1abc\0\164\0\u1af6\0\u1b30"+
    "\0\u1b6a\0\u1ba4\0\u1bde\0\u1c18\0\164\0\u1c52\0\164\0\u1c8c"+
    "\0\164\0\72\0\164\0\u1cc6\0\u1d00\0\72\0\u1d3a\0\u1d74"+
    "\0\164\0\u1dae\0\u1de8\0\u1e22\0\u1e5c\0\u1e96\0\u1ed0\0\u1f0a"+
    "\0\u1f44\0\72\0\164\0\164\0\u1f7e\0\u1fb8\0\u1ff2\0\u202c"+
    "\0\u2066\0\72\0\72\0\u20a0\0\72\0\164\0\u20da\0\u2114"+
    "\0\u214e\0\u2188\0\164\0\u0b8e\0\72\0\164\0\164\0\u21c2"+
    "\0\u21fc\0\u2236\0\u2270\0\72\0\164\0\u22aa\0\u22e4\0\u231e"+
    "\0\u2358\0\164\0\164\0\164\0\u2392\0\u23cc\0\u2406\0\u2440"+
    "\0\u247a\0\u24b4\0\u24ee\0\u2528\0\u2562\0\u259c\0\u25d6\0\u2610"+
    "\0\u264a\0\164\0\u2684\0\u26be\0\164\0\72\0\164\0\u26f8"+
    "\0\u2732\0\72\0\164\0\u276c\0\u27a6\0\u27e0\0\u281a\0\u2854"+
    "\0\u288e\0\72\0\164\0\u28c8\0\u2902\0\u293c\0\72\0\164"+
    "\0\72\0\164\0\u2976\0\u29b0\0\u29ea\0\u2a24\0\164\0\164"+
    "\0\72\0\164\0\u2a5e\0\u2a98\0\u2ad2\0\u2b0c\0\u2b46\0\u2b80"+
    "\0\u2bba\0\u2bf4\0\72\0\164\0\u2c2e\0\u2c68\0\72\0\164"+
    "\0\u2ca2\0\u2854\0\u2cdc\0\164\0\164\0\72\0\164\0\u2d16"+
    "\0\u2d50\0\u2d8a\0\u2dc4\0\72\0\164\0\72\0\u2dfe\0\164"+
    "\0\u2e38\0\164\0\u2e72\0\u2eac\0\u2ee6\0\164\0\72\0\164"+
    "\0\164\0\u2f20\0\u2f5a\0\u2f94\0\164\0\u2fce\0\u3008\0\u3042"+
    "\0\72\0\164\0\72\0\164\0\164";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[309];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\2\1\13\2\4\1\14\1\0\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\2\24\1\25\1\26"+
    "\1\27\2\30\1\3\1\31\1\32\1\33\1\34\2\35"+
    "\1\3\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\2\1\3\2\45\1\13\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\73\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\11\0\1\56\1\4\2\0\1\56\1\0"+
    "\1\57\3\0\1\56\2\4\7\0\5\56\1\0\14\56"+
    "\1\0\5\56\1\0\4\56\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\4\3\1\60\3\3"+
    "\2\61\2\3\1\0\5\3\1\0\4\3\12\0\1\62"+
    "\3\0\1\63\5\0\2\62\2\0\1\64\44\0\1\65"+
    "\6\0\1\66\11\0\2\66\54\0\4\67\1\0\3\67"+
    "\1\0\1\67\1\70\57\67\11\71\1\72\1\73\57\71"+
    "\1\0\2\3\2\0\1\74\5\0\3\3\7\0\1\3"+
    "\1\75\3\3\1\0\12\3\1\76\1\3\1\0\5\3"+
    "\1\0\4\3\26\0\1\77\46\0\1\100\25\0\1\101"+
    "\2\0\1\102\132\0\1\103\6\0\1\104\11\0\2\104"+
    "\56\0\1\62\11\0\2\62\2\0\1\64\3\0\1\105"+
    "\40\0\1\106\5\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\1\3\1\107\3\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\2\3\2\110\1\3\1\0\14\3\1\0\5\3"+
    "\1\0\1\3\2\111\1\3\11\0\2\3\2\0\1\112"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\2\3\2\113\1\3\1\114\1\115\2\3\1\116"+
    "\10\3\1\0\5\3\1\0\4\3\53\0\2\117\12\0"+
    "\2\120\12\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\0\10\3\2\121\2\3\1\0\5\3\1\0"+
    "\1\3\2\122\1\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\1\3\1\123\2\124\1\3\1\0\3\3"+
    "\1\125\6\3\1\126\1\3\1\0\5\3\1\0\4\3"+
    "\11\0\2\3\2\0\1\3\5\0\3\3\7\0\1\3"+
    "\1\127\3\3\1\0\6\3\1\130\5\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\6\3\1\131\5\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\2\3\2\132\1\3\1\0\10\3\2\133\2\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\10\3\2\134\2\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\1\3\1\135\3\3\1\136\1\137"+
    "\13\3\1\0\5\3\1\0\4\3\11\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\2\3\2\140\1\3\1\0"+
    "\6\3\1\141\5\3\1\0\5\3\1\0\4\3\15\0"+
    "\1\142\26\0\2\143\1\144\34\0\2\3\2\0\1\145"+
    "\5\0\3\3\7\0\5\3\1\0\1\3\2\146\1\147"+
    "\10\3\1\0\5\3\1\0\4\3\11\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\1\3\1\150\3\3\1\0"+
    "\14\3\1\0\5\3\1\0\4\3\11\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\1\3\1\151\3\3\1\0"+
    "\3\3\1\152\2\3\1\153\5\3\1\0\5\3\1\0"+
    "\4\3\11\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\1\3\1\154\3\3\1\155\1\156\13\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\1\3\1\157\3\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\1\3\1\160\3\3\1\161\1\162\5\3\1\163"+
    "\1\164\4\3\1\0\5\3\1\0\4\3\74\0\1\165"+
    "\1\166\70\0\1\167\1\170\1\171\70\0\1\172\5\0"+
    "\2\56\2\0\1\56\1\0\1\173\3\0\3\56\7\0"+
    "\5\56\1\0\14\56\1\0\5\56\1\0\4\56\11\0"+
    "\1\173\1\174\2\0\1\173\5\0\1\173\2\174\7\0"+
    "\5\173\1\0\14\173\1\0\5\173\1\0\4\173\11\0"+
    "\2\3\2\0\1\3\5\0\3\3\7\0\5\3\1\0"+
    "\14\3\1\175\1\176\4\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\14\3"+
    "\1\0\3\3\1\177\1\3\1\0\4\3\12\0\1\62"+
    "\4\0\1\200\4\0\2\62\100\0\1\102\55\0\1\201"+
    "\71\0\4\67\1\202\1\203\12\0\1\67\4\0\1\67"+
    "\6\0\1\67\13\0\1\67\21\0\6\71\12\0\1\71"+
    "\4\0\1\71\6\0\1\71\13\0\1\71\12\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\14\3"+
    "\1\0\1\3\1\204\3\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\1\3\1\205\3\3"+
    "\1\0\14\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\1\3"+
    "\2\206\11\3\1\0\5\3\1\0\4\3\10\0\4\77"+
    "\1\0\12\77\1\0\52\77\11\101\1\0\1\207\6\101"+
    "\1\210\50\101\2\0\1\211\11\0\2\211\55\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\2\3\2\212\1\3"+
    "\1\0\14\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\6\3"+
    "\1\213\4\3\1\214\1\0\2\3\1\215\2\3\1\0"+
    "\4\3\11\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\216\1\217\13\3\1\0\5\3\1\0\4\3"+
    "\44\0\2\220\35\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\1\3\2\221\11\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\222\1\223\13\3\1\0\5\3\1\0"+
    "\4\3\44\0\2\224\1\0\1\225\33\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\5\3\1\0\1\3\2\226"+
    "\1\3\1\227\7\3\1\0\5\3\1\0\4\3\11\0"+
    "\2\3\2\0\1\3\5\0\3\3\7\0\5\3\1\0"+
    "\7\3\1\230\4\3\1\0\5\3\1\0\4\3\11\0"+
    "\2\3\2\0\1\231\5\0\3\3\7\0\5\3\1\0"+
    "\14\3\1\0\5\3\1\0\4\3\11\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\5\3\1\0\13\3\1\232"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\10\3\2\233\2\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\1\234\2\3\7\0\5\3\1\0\14\3\1\0"+
    "\5\3\1\0\3\3\1\234\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\2\3\2\235\1\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\2\3\2\236\1\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\3\3"+
    "\1\237\1\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\1\3\2\240\11\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\1\3\2\241\11\3"+
    "\1\0\5\3\1\0\4\3\47\0\1\242\33\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\4\3"+
    "\1\243\7\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\1\3\1\244\3\3"+
    "\1\0\14\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\14\3"+
    "\1\0\2\3\1\245\2\3\1\0\4\3\44\0\2\246"+
    "\63\0\2\247\67\0\1\250\44\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\1\3\2\251\11\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\2\3\2\252\1\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\1\3\1\253\3\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\1\3\2\254\11\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\10\3\2\255\2\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\6\3\1\256\5\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\257\1\260"+
    "\4\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\4\3\1\261\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\50\0\1\262\32\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\5\3\1\263\6\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\3\3"+
    "\1\264\1\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\2\3\2\265\1\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\47\0\1\266\33\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\4\3"+
    "\1\267\7\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\4\3"+
    "\1\270\7\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\10\3"+
    "\2\271\2\3\1\0\5\3\1\0\4\3\75\0\1\272"+
    "\71\0\1\273\5\0\2\173\2\0\1\173\5\0\3\173"+
    "\7\0\5\173\1\0\14\173\1\0\5\173\1\0\4\173"+
    "\11\0\1\173\1\174\2\0\1\274\5\0\1\173\2\174"+
    "\7\0\5\173\1\0\14\173\1\0\5\173\1\0\4\173"+
    "\15\0\1\275\65\0\2\3\2\0\1\276\5\0\3\3"+
    "\7\0\5\3\1\0\14\3\1\0\5\3\1\0\4\3"+
    "\12\0\1\277\11\0\2\277\64\0\1\201\3\0\2\67"+
    "\64\0\1\201\3\0\2\202\55\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\300\1\301\13\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\0\4\3\1\302\7\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\303\5\0"+
    "\3\3\7\0\5\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\20\0\6\101\12\0\1\101\4\0\1\101\6\0"+
    "\1\101\13\0\1\101\11\0\11\101\1\0\1\207\6\101"+
    "\1\210\1\304\47\101\2\0\1\211\11\0\2\211\4\0"+
    "\1\305\50\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\0\4\3\1\306\7\3\1\0\3\3\1\307"+
    "\1\3\1\0\4\3\11\0\2\3\2\0\1\310\5\0"+
    "\3\3\7\0\5\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\11\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\1\3\1\311\3\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\44\0\2\312\35\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\0\1\3\2\313\11\3\1\0"+
    "\5\3\1\0\4\3\46\0\1\314\34\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\5\3\1\0\3\3\1\315"+
    "\10\3\1\0\5\3\1\0\4\3\47\0\1\316\33\0"+
    "\2\3\2\0\1\3\5\0\3\3\7\0\5\3\1\0"+
    "\4\3\1\317\7\3\1\0\5\3\1\0\4\3\42\0"+
    "\2\320\37\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\320\1\321\13\3\1\0\5\3\1\0\4\3"+
    "\11\0\2\3\2\0\1\322\5\0\3\3\7\0\5\3"+
    "\1\0\14\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\10\3"+
    "\2\323\2\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\324\5\0\3\3\7\0\5\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\1\3"+
    "\1\325\3\3\1\0\4\3\11\0\2\3\2\0\1\326"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\6\3\1\327\5\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\330\1\331\13\3\1\0\5\3\1\0"+
    "\4\3\11\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\0\14\3\1\0\1\3\1\332\1\333\2\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\14\3\1\0\5\3\1\334\1\335"+
    "\3\3\42\0\2\336\65\0\2\337\42\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\5\3\1\336\1\340\13\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\2\3\2\341\1\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\1\3\1\342\3\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\343\1\344"+
    "\4\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\2\3\2\345\1\3\1\0\14\3\1\0"+
    "\5\3\1\0\4\3\15\0\1\346\65\0\2\3\2\0"+
    "\1\347\5\0\3\3\7\0\5\3\1\0\14\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\0\10\3\2\350\2\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\4\3\1\351\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\15\0\1\352\65\0\2\3\2\0\1\353"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\14\3\1\354\1\355\4\3\1\0"+
    "\4\3\11\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\0\14\3\1\0\2\3\1\356\2\3\1\0"+
    "\4\3\11\0\1\173\1\357\2\0\1\173\1\360\4\0"+
    "\1\173\2\357\6\0\1\360\5\173\1\0\14\173\1\0"+
    "\5\173\1\0\4\173\12\0\1\277\2\0\1\361\6\0"+
    "\2\277\117\0\2\362\26\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\0\10\3\2\363\2\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\364\5\0"+
    "\3\3\7\0\5\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\11\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\0\6\3\1\365\5\3\1\0\5\3\1\0"+
    "\4\3\11\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\2\3\2\366\1\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\15\0\1\367\65\0\2\3\2\0\1\370\5\0"+
    "\3\3\7\0\5\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\15\0\1\371\65\0\2\3\2\0\1\372\5\0"+
    "\3\3\7\0\5\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\53\0\2\373\26\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\0\10\3\2\374\2\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\375\1\376\13\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\4\3\1\377\7\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\12\3\1\u0100\1\3\1\0\5\3"+
    "\1\0\4\3\47\0\1\u0101\33\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\4\3\1\u0102\7\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\2\3\2\u0103\1\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\u0104"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\15\0\1\u0105\65\0\2\3\2\0\1\u0106"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\5\3"+
    "\1\0\4\3\53\0\2\u0107\61\0\2\u0108\35\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\10\3"+
    "\2\u0109\2\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\1\3"+
    "\2\u010a\11\3\1\0\5\3\1\0\4\3\44\0\2\u010b"+
    "\35\0\2\3\2\0\1\3\5\0\3\3\7\0\5\3"+
    "\1\0\1\3\2\u010c\11\3\1\0\5\3\1\0\4\3"+
    "\11\0\2\3\2\0\1\3\5\0\3\3\7\0\5\3"+
    "\1\0\1\3\2\u010d\11\3\1\0\5\3\1\0\4\3"+
    "\11\0\2\3\2\0\1\3\5\0\3\3\7\0\5\3"+
    "\1\0\6\3\1\u010e\5\3\1\0\5\3\1\0\4\3"+
    "\15\0\1\u010f\65\0\2\3\2\0\1\u0110\5\0\3\3"+
    "\7\0\5\3\1\0\14\3\1\0\5\3\1\0\4\3"+
    "\11\0\2\3\2\0\1\3\5\0\3\3\7\0\5\3"+
    "\1\0\1\3\2\u0111\11\3\1\0\5\3\1\0\4\3"+
    "\11\0\1\173\1\357\2\0\1\173\5\0\1\173\2\357"+
    "\7\0\5\173\1\0\14\173\1\0\5\173\1\0\4\173"+
    "\12\0\1\u0112\11\0\2\u0112\56\0\1\u0112\3\0\1\360"+
    "\5\0\2\u0112\6\0\1\360\46\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\6\3\1\u0113\5\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\1\3\2\u0114\11\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\3\3"+
    "\1\u0115\1\3\1\0\4\3\15\0\1\u0116\65\0\2\3"+
    "\2\0\1\u0117\5\0\3\3\7\0\5\3\1\0\14\3"+
    "\1\0\5\3\1\0\4\3\53\0\2\u0118\26\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\10\3"+
    "\2\u0119\2\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\6\3"+
    "\1\u011a\5\3\1\0\5\3\1\0\4\3\11\0\2\3"+
    "\2\0\1\3\5\0\3\3\7\0\5\3\1\0\14\3"+
    "\1\0\3\3\1\u011b\1\3\1\0\4\3\63\0\1\u011c"+
    "\17\0\2\3\2\0\1\3\5\0\3\3\7\0\5\3"+
    "\1\0\14\3\1\0\3\3\1\u011d\1\3\1\0\4\3"+
    "\61\0\1\u011e\52\0\2\u011f\37\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\1\3"+
    "\1\u0120\3\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\u011f\1\u0121\13\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\1\3\1\u0122\3\3\1\0\14\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\2\3\2\u0123\1\3\1\0\14\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\u0124\1\u0125\13\3\1\0\5\3"+
    "\1\0\4\3\11\0\2\3\2\0\1\3\5\0\3\3"+
    "\7\0\5\3\1\0\10\3\2\u0126\2\3\1\0\5\3"+
    "\1\0\4\3\44\0\2\u0127\35\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\1\3\2\u0128\11\3"+
    "\1\0\5\3\1\0\4\3\11\0\2\3\2\0\1\3"+
    "\5\0\3\3\7\0\5\3\1\0\14\3\1\0\4\3"+
    "\1\u0129\1\0\4\3\11\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\0\7\3\1\u012a\4\3\1\0"+
    "\5\3\1\0\4\3\53\0\2\u012b\26\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\5\3\1\0\10\3\2\u012c"+
    "\2\3\1\0\5\3\1\0\4\3\11\0\2\3\2\0"+
    "\1\3\5\0\3\3\7\0\5\3\1\0\14\3\1\0"+
    "\3\3\1\u012d\1\3\1\0\4\3\36\0\1\u012e\44\0"+
    "\2\3\2\0\1\3\5\0\3\3\7\0\1\3\1\u012f"+
    "\3\3\1\0\14\3\1\0\5\3\1\0\4\3\11\0"+
    "\2\3\2\0\1\3\5\0\3\3\7\0\2\3\2\u0130"+
    "\1\3\1\0\14\3\1\0\5\3\1\0\4\3\44\0"+
    "\2\u0131\35\0\2\3\2\0\1\3\5\0\3\3\7\0"+
    "\5\3\1\0\1\3\2\u0132\11\3\1\0\5\3\1\0"+
    "\4\3\53\0\2\u0133\26\0\2\3\2\0\1\3\5\0"+
    "\3\3\7\0\5\3\1\0\10\3\2\u0134\2\3\1\0"+
    "\5\3\1\0\4\3\11\0\2\3\2\0\1\u0135\5\0"+
    "\3\3\7\0\5\3\1\0\14\3\1\0\5\3\1\0"+
    "\4\3\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12412];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\11\1\1\11\26\1\2\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\5\1\1\11"+
    "\1\0\1\11\1\1\3\0\1\11\1\0\4\1\1\11"+
    "\2\0\1\11\1\1\2\11\5\1\1\0\3\1\1\11"+
    "\15\1\1\0\3\1\3\0\10\1\1\0\3\1\1\0"+
    "\4\1\3\11\1\1\1\11\2\1\1\0\2\1\1\0"+
    "\1\11\2\0\3\1\3\0\4\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\0\14\1\1\11\3\1"+
    "\1\11\2\0\6\1\1\0\2\1\1\11\3\1\1\0"+
    "\3\1\2\11\1\1\1\11\2\1\1\0\4\1\1\11"+
    "\4\1\1\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\7\1\1\0\3\1\1\0\1\1\2\0\3\1\1\0"+
    "\2\1\1\11\3\1\1\11\1\1\1\0\3\1\2\0"+
    "\1\11\4\1\1\11\1\1\1\11\1\1\1\0\1\1"+
    "\1\0\3\1\1\11\3\1\1\0\1\1\2\0\2\1"+
    "\1\11\3\1\1\11\6\1\1\11\1\1\1\0\3\1"+
    "\1\11\1\1\1\11\1\0\4\1\1\0\2\1\1\11"+
    "\3\1\1\0\2\1\1\0\2\1\1\11\1\1\1\11"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[309];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 232) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext(); return ERROR;
            }
          case 87: break;
          case 2: 
            { lexeme=yytext(); return IDENTIFICADOR;
            }
          case 88: break;
          case 3: 
            { lexeme=yytext(); return LITERAL_ENTERO;
            }
          case 89: break;
          case 4: 
            { /*Ignore*/
            }
          case 90: break;
          case 5: 
            { lexeme = "+"; return OPERADOR;
            }
          case 91: break;
          case 6: 
            { lexeme = "."; return OPERADOR;
            }
          case 92: break;
          case 7: 
            { lexeme = "/"; return OPERADOR;
            }
          case 93: break;
          case 8: 
            { lexeme = "("; return OPERADOR;
            }
          case 94: break;
          case 9: 
            { lexeme = "*"; return OPERADOR;
            }
          case 95: break;
          case 10: 
            { lexeme = ")"; return OPERADOR;
            }
          case 96: break;
          case 11: 
            { lexeme = "-"; return OPERADOR;
            }
          case 97: break;
          case 12: 
            { lexeme = "]"; return OPERADOR;
            }
          case 98: break;
          case 13: 
            { lexeme = "["; return OPERADOR;
            }
          case 99: break;
          case 14: 
            { lexeme = ">"; return OPERADOR;
            }
          case 100: break;
          case 15: 
            { lexeme = "="; return OPERADOR;
            }
          case 101: break;
          case 16: 
            { lexeme = "<"; return OPERADOR;
            }
          case 102: break;
          case 17: 
            { lexeme = ";"; return OPERADOR;
            }
          case 103: break;
          case 18: 
            { lexeme = ":"; return OPERADOR;
            }
          case 104: break;
          case 19: 
            { lexeme = ","; return OPERADOR;
            }
          case 105: break;
          case 20: 
            { lexeme = "++"; return OPERADOR;
            }
          case 106: break;
          case 21: 
            { lexeme = "+="; return OPERADOR;
            }
          case 107: break;
          case 22: 
            { lexeme=yytext(); return LITERAL_STRING;
            }
          case 108: break;
          case 23: 
            { lexeme = "/="; return OPERADOR;
            }
          case 109: break;
          case 24: 
            { lexeme = "*="; return OPERADOR;
            }
          case 110: break;
          case 25: 
            { lexeme=yytext(); return LITERAL_CHAR;
            }
          case 111: break;
          case 26: 
            { lexeme = "--"; return OPERADOR;
            }
          case 112: break;
          case 27: 
            { lexeme = "-="; return OPERADOR;
            }
          case 113: break;
          case 28: 
            { lexeme = "OR"; return OPERADOR;
            }
          case 114: break;
          case 29: 
            { lexeme = "OF"; return PALABRAS_RESERVADAS;
            }
          case 115: break;
          case 30: 
            { lexeme = "IN"; return PALABRAS_RESERVADAS;
            }
          case 116: break;
          case 31: 
            { lexeme = "IF"; return PALABRAS_RESERVADAS;
            }
          case 117: break;
          case 32: 
            { lexeme = "TO"; return PALABRAS_RESERVADAS;
            }
          case 118: break;
          case 33: 
            { lexeme = "DO"; return PALABRAS_RESERVADAS;
            }
          case 119: break;
          case 34: 
            { lexeme = ">>"; return OPERADOR;
            }
          case 120: break;
          case 35: 
            { lexeme = ">="; return OPERADOR;
            }
          case 121: break;
          case 36: 
            { lexeme = "<>"; return OPERADOR;
            }
          case 122: break;
          case 37: 
            { lexeme = "<="; return OPERADOR;
            }
          case 123: break;
          case 38: 
            { lexeme = "<<"; return OPERADOR;
            }
          case 124: break;
          case 39: 
            { lexeme = ":="; return OPERADOR;
            }
          case 125: break;
          case 40: 
            { lexeme=yytext(); return LITERAL_FLOTANTE;
            }
          case 126: break;
          case 41: 
            { lexeme = "END"; return PALABRAS_RESERVADAS;
            }
          case 127: break;
          case 42: 
            { lexeme = "XOR"; return OPERADOR;
            }
          case 128: break;
          case 43: 
            { lexeme = "INT"; return PALABRAS_RESERVADAS;
            }
          case 129: break;
          case 44: 
            { lexeme = "VAR"; return PALABRAS_RESERVADAS;
            }
          case 130: break;
          case 45: 
            { lexeme = "AND"; return OPERADOR;
            }
          case 131: break;
          case 46: 
            { lexeme = "NOT"; return OPERADOR;
            }
          case 132: break;
          case 47: 
            { lexeme = "NIL"; return PALABRAS_RESERVADAS;
            }
          case 133: break;
          case 48: 
            { lexeme = "SET"; return PALABRAS_RESERVADAS;
            }
          case 134: break;
          case 49: 
            { lexeme = "DIV"; return OPERADOR;
            }
          case 135: break;
          case 50: 
            { lexeme = "MOD"; return OPERADOR;
            }
          case 136: break;
          case 51: 
            { lexeme = "FOR"; return PALABRAS_RESERVADAS;
            }
          case 137: break;
          case 52: 
            { lexeme = ">>="; return OPERADOR;
            }
          case 138: break;
          case 53: 
            { lexeme = "<<="; return OPERADOR;
            }
          case 139: break;
          case 54: 
            { lexeme = "ELSE"; return PALABRAS_RESERVADAS;
            }
          case 140: break;
          case 55: 
            { lexeme = "BYTE"; return PALABRAS_RESERVADAS;
            }
          case 141: break;
          case 56: 
            { lexeme = "REAL"; return PALABRAS_RESERVADAS;
            }
          case 142: break;
          case 57: 
            { lexeme = "READ"; return PALABRAS_RESERVADAS;
            }
          case 143: break;
          case 58: 
            { lexeme = "WITH"; return PALABRAS_RESERVADAS;
            }
          case 144: break;
          case 59: 
            { lexeme = "TRUE"; return PALABRAS_RESERVADAS;
            }
          case 145: break;
          case 60: 
            { lexeme = "THEN"; return PALABRAS_RESERVADAS;
            }
          case 146: break;
          case 61: 
            { lexeme = "TYPE"; return PALABRAS_RESERVADAS;
            }
          case 147: break;
          case 62: 
            { lexeme = "GOTO"; return PALABRAS_RESERVADAS;
            }
          case 148: break;
          case 63: 
            { lexeme = "CHAR"; return PALABRAS_RESERVADAS;
            }
          case 149: break;
          case 64: 
            { lexeme = "CASE"; return PALABRAS_RESERVADAS;
            }
          case 150: break;
          case 65: 
            { lexeme = "FILE"; return PALABRAS_RESERVADAS;
            }
          case 151: break;
          case 66: 
            { lexeme = "BEGIN"; return PALABRAS_RESERVADAS;
            }
          case 152: break;
          case 67: 
            { lexeme = "WRITE"; return PALABRAS_RESERVADAS;
            }
          case 153: break;
          case 68: 
            { lexeme = "WHILE"; return PALABRAS_RESERVADAS;
            }
          case 154: break;
          case 69: 
            { lexeme = "LABEL"; return PALABRAS_RESERVADAS;
            }
          case 155: break;
          case 70: 
            { lexeme = "ARRAY"; return PALABRAS_RESERVADAS;
            }
          case 156: break;
          case 71: 
            { lexeme = "UNTIL"; return PALABRAS_RESERVADAS;
            }
          case 157: break;
          case 72: 
            { lexeme = "CONST"; return PALABRAS_RESERVADAS;
            }
          case 158: break;
          case 73: 
            { lexeme = "FALSE"; return PALABRAS_RESERVADAS;
            }
          case 159: break;
          case 74: 
            { lexeme = "REPEAT"; return PALABRAS_RESERVADAS;
            }
          case 160: break;
          case 75: 
            { lexeme = "RECORD"; return PALABRAS_RESERVADAS;
            }
          case 161: break;
          case 76: 
            { lexeme = "INLINE"; return PALABRAS_RESERVADAS;
            }
          case 162: break;
          case 77: 
            { lexeme = "PACKED"; return PALABRAS_RESERVADAS;
            }
          case 163: break;
          case 78: 
            { lexeme = "STRING"; return PALABRAS_RESERVADAS;
            }
          case 164: break;
          case 79: 
            { lexeme = "DOWNTO"; return PALABRAS_RESERVADAS;
            }
          case 165: break;
          case 80: 
            { lexeme = "BOOLEAN"; return PALABRAS_RESERVADAS;
            }
          case 166: break;
          case 81: 
            { lexeme = "LONGINT"; return PALABRAS_RESERVADAS;
            }
          case 167: break;
          case 82: 
            { lexeme = "PROGRAM"; return PALABRAS_RESERVADAS;
            }
          case 168: break;
          case 83: 
            { lexeme = "FORWARD"; return PALABRAS_RESERVADAS;
            }
          case 169: break;
          case 84: 
            { lexeme = "SHORTINT"; return PALABRAS_RESERVADAS;
            }
          case 170: break;
          case 85: 
            { lexeme = "FUNCTION"; return PALABRAS_RESERVADAS;
            }
          case 171: break;
          case 86: 
            { lexeme = "PROCEDURE"; return PALABRAS_RESERVADAS;
            }
          case 172: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

    public int getYyline() 
    {
        return yyline;
    }


}
